INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (1, 123.45);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (2, 1.0);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (3, 150.0);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (4, 200.00);
